'''Build configuration file of problems in maths.'''

py_binary(
    name="euclids_theorem",
    srcs=["euclids_theorem.py"],
    main="euclids_theorem.py",
)

py_binary(
    name="matrices",
    srcs=["matrices.py"],
    main="matrices.py",
)
