py_binary(
    name = "list_of_lists_tree",
    srcs = ["list_of_lists_tree.py"],
    main = "list_of_lists_tree.py",
)

py_binary(
    name = "nodes_and_refs",
    srcs = ["nodes_and_refs.py"],
    main = "nodes_and_refs.py",
)
