'''Build configuration file for linked_list files.'''

py_binary(
    name="ascend_order_llist",
    srcs=["ascend_order_llist.py"],
    main="ascend_order_llist.py",
)

py_binary(
    name="circular_llist_ops",
    srcs=["circular_llist_ops.py"],
    main="circular_llist_ops.py",
)

py_binary(
    name="circular_llist",
    srcs=["circular_llist.py"],
    main="circular_llist.py",
)

py_binary(
    name="linked_list_ops",
    srcs=["linked_list_ops.py"],
    main="linked_list_ops.py",
)

py_binary(
    name="merging_llist",
    srcs=["merging_llist.py"],
    main="merging_llist.py",
)

py_binary(
    name="reverse_llist",
    srcs=["reverse_llist.py"],
    main="reverse_llist.py",
)

py_binary(
    name="sort_llist_01",
    srcs=["sort_llist_01.py"],
    main="sort_llist_01.py",
)
