py_binary(
    name = "multi_th_priority_queue",
    srcs = ["multi_th_priority_queue.py"],
    main = "multi_th_priority_queue.py",
)

py_binary(
    name = "nonsync_threads",
    srcs = ["nonsync_threads.py"],
    main = "nonsync_threads.py",
)

py_binary(
    name = "sync_threads",
    srcs = ["sync_threads.py"],
    main = "sync_threads.py",
)