py_binary(
    name = "helloworld",
    srcs = ["helloworld.py"],
    main = "helloworld.py",
)

py_test(
    name = "helloworld_test",
    srcs = ["helloworld_test.py",
    ],
    deps = [":helloworld",
    ],
)
