py_binary(
    name = "searching_algs_bin",
    srcs = ["searching_algs.py"],
    main = "searching_algs.py",
)

py_test(
    name = "searching_algs_test",
    srcs = ["searching_algs_test.py",
    ],
    deps = [":searching_algs_bin",
    ],
)
